[CmdletBinding()]
param(
    [string]$ResourceGroup = 'rg-aigw-lab',
    [string]$Location = 'swedencentral',
    [string]$SecondaryLocation = 'francecentral',
    [string]$ModelName = 'gpt-4o',
    [string]$ModelVersion = '2024-11-20',
    [int]$DeploymentCapacity = 50,
    [string]$DeploymentAlias = 'chat',
    [switch]$WhatIf
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$script:logFile = Join-Path $repoRoot 'deploy.log'
function Log($msg) {
    $line = "[{0}] {1}" -f (Get-Date -Format 's'), $msg
    Write-Host $line
    Add-Content -Path $script:logFile -Value $line
}

# Reset run log
"=== deploy.ps1 run @ $(Get-Date -Format s) ===" | Out-File -FilePath $script:logFile -Encoding utf8

# 1. az login state
Log 'Checking az login...'
$ctx = az account show --only-show-errors 2>$null | ConvertFrom-Json
if (-not $ctx) {
    Log 'az login required'
    az login --only-show-errors | Out-Null
    $ctx = az account show | ConvertFrom-Json
}
Log ("Subscription: {0} ({1}) - user {2}" -f $ctx.name, $ctx.id, $ctx.user.name)

# 2. Tags
$tagPairs = @(
    'Owner=admin@example.com',
    'Project=apim-ai-gateway-lab',
    'SecurityControl=Ignore'
)

# 3. Quota check
Log "Checking AOAI Standard.$ModelName quota in $Location and $SecondaryLocation..."
foreach ($loc in @($Location, $SecondaryLocation)) {
    $all = az cognitiveservices usage list --location $loc -o json 2>$null | ConvertFrom-Json
    $q = $all | Where-Object { $_.name.value -eq "OpenAI.Standard.$ModelName" } | Select-Object -First 1
    if (-not $q) {
        Log "  WARNING: no Standard.$ModelName quota visible in $loc"
    } else {
        $remain = [double]$q.limit - [double]$q.currentValue
        Log ("  {0}: limit={1} used={2} remaining={3}" -f $loc, $q.limit, $q.currentValue, $remain)
    }
}

# 4. RG
Log "Ensuring RG $ResourceGroup in $Location..."
az group create --name $ResourceGroup --location $Location --tags @tagPairs --only-show-errors | Out-Null

# 5. Deploy
$deploymentName = "aigw-lab-$(Get-Date -Format yyyyMMddHHmmss)"
$bicepPath = Join-Path $repoRoot 'infra\main.bicep'
$cmd = @(
    'deployment', 'group', $(if ($WhatIf) { 'what-if' } else { 'create' }),
    '--name', $deploymentName,
    '--resource-group', $ResourceGroup,
    '--template-file', $bicepPath,
    '--parameters',
        "primaryLocation=$Location",
        "secondaryLocation=$SecondaryLocation",
        "modelName=$ModelName",
        "modelVersion=$ModelVersion",
        "deploymentCapacity=$DeploymentCapacity",
        "deploymentAlias=$DeploymentAlias",
    '--only-show-errors'
)
Log ("Running: az {0}" -f ($cmd -join ' '))
$out = az @cmd 2>&1
$exit = $LASTEXITCODE
$out | Out-String | Add-Content -Path $script:logFile
if ($exit -ne 0) {
    Log "Deployment FAILED (exit $exit). See run.log."
    exit $exit
}
if ($WhatIf) { Log 'what-if complete'; return }

# 6. Outputs
$outputs = az deployment group show --resource-group $ResourceGroup --name $deploymentName --query properties.outputs -o json | ConvertFrom-Json
$apimName = $outputs.apimName.value
$gwUrl = $outputs.apimGatewayUrl.value
$alias = $outputs.deploymentAlias.value

# 7. Per-tier subscription keys (emitted as @secure() outputs from main.bicep)
Log "Reading per-tier subscription keys from deployment outputs..."
$keyFast = $outputs.subscriptionKeyFast.value
$keyStd = $outputs.subscriptionKeyStandard.value
$keyBatch = $outputs.subscriptionKeyBatch.value
$extKey = $outputs.externalSubscriptionKey.value
$mcpKey = $outputs.mcpSubscriptionKey.value
$extPath = $outputs.externalApiPath.value
$mcpPath = $outputs.mcpApiPath.value

$envFile = Join-Path $repoRoot '.demo.env'
@(
    "# Generated by scripts/deploy.ps1, do NOT commit"
    "GATEWAY_URL=$gwUrl",
    "APIM_NAME=$apimName",
    "DEPLOYMENT_ALIAS=$alias",
    "MODEL_NAME=$ModelName",
    "RESOURCE_GROUP=$ResourceGroup",
    "KEY_FAST=$keyFast",
    "KEY_STANDARD=$keyStd",
    "KEY_BATCH=$keyBatch",
    "EXTERNAL_GATEWAY_URL=$gwUrl$extPath",
    "EXTERNAL_GATEWAY_KEY=$extKey",
    "MCP_GATEWAY_URL=$gwUrl$mcpPath",
    "MCP_GATEWAY_KEY=$mcpKey",
    "AOAI_PRIMARY_NAME=$($outputs.aoaiPrimaryName.value)",
    "AOAI_SECONDARY_NAME=$($outputs.aoaiSecondaryName.value)",
    "AOAI_TERTIARY_NAME=$($outputs.aoaiTertiaryName.value)",
    "APP_INSIGHTS_NAME=$($outputs.appInsightsName.value)",
    "WORKSPACE_NAME=$($outputs.workspaceName.value)",
    "REDIS_NAME=$($outputs.redisName.value)",
    "CONTENT_SAFETY_NAME=$($outputs.contentSafetyName.value)"
) | Out-File -FilePath $envFile -Encoding utf8

Log "=== Deployment complete ==="
Log "Gateway URL : $gwUrl"
Log "API path    : /openai/deployments/$alias/chat/completions?api-version=2024-10-21"
Log "Env file    : $envFile (KEY_FAST/KEY_STANDARD/KEY_BATCH for tier products)"
Log ""
Log "Run tests:   pwsh tests/test.ps1 -Scenario all"
